[project]
name = "strava-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andy Davies", email = "andrew.m.davies.2@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "core",
    "gpxpy>=1.6.2",
    "httpx[http2]>=0.28.1",
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
    "pydantic>=2.12.5",
]

[tool.uv.sources]
core = { workspace = true }

[build-system]
requires = ["uv_build>=0.9.29,<0.10.0"]
build-backend = "uv_build"
